workspace:
  base: /go
  path: src/megpoid.xyz/go/go-s3-backup

pipeline:
  test:
    image: golang:1.10
    commands:
    - go get -u golang.org/x/lint/golint
    - go vet ./...
    - go test -v ./...
    - golint -set_exit_status `find . -type d -not -path "./vendor*" -not -path "./.git*"`

  publish:
    image: plugins/docker
    repo: registry.megpoid.xyz/go-s3-backup
    registry: registry.megpoid.xyz
    mirror: https://registry-proxy.megpoid.xyz
    secrets: [ docker_username, docker_password ]
    build_args:
    - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    - COMMIT_SHA=${DRONE_COMMIT_SHA}
    tags:
    - latest

  publish-gogs:
    image: plugins/docker
    repo: registry.megpoid.xyz/gogs-s3-backup
    dockerfile: docker/gogs/Dockerfile
    registry: registry.megpoid.xyz
    mirror: https://registry-proxy.megpoid.xyz
    secrets: [ docker_username, docker_password ]
    tags:
    - latest

  publish-mysql:
    image: plugins/docker
    repo: registry.megpoid.xyz/mysql-s3-backup
    dockerfile: docker/mysql/Dockerfile
    registry: registry.megpoid.xyz
    mirror: https://registry-proxy.megpoid.xyz
    secrets: [ docker_username, docker_password ]
    tags:
    - latest

  publish-postgres:
    image: plugins/docker
    repo: registry.megpoid.xyz/postgres-s3-backup
    dockerfile: docker/postgres/Dockerfile
    registry: registry.megpoid.xyz
    mirror: https://registry-proxy.megpoid.xyz
    secrets: [ docker_username, docker_password ]
    tags:
    - latest

  publish-consul:
    image: plugins/docker
    repo: registry.megpoid.xyz/consul-s3-backup
    dockerfile: docker/consul/Dockerfile
    registry: registry.megpoid.xyz
    mirror: https://registry-proxy.megpoid.xyz
    secrets: [ docker_username, docker_password ]
    tags:
    - latest

  dockerhub:
    image: plugins/docker
    repo: codestation/go-s3-backup
    mirror: https://registry-proxy.megpoid.xyz
    secrets:
    - source: dockerhub_username
      target: docker_username
    - source: dockerhub_password
      target: docker_password
    build_args:
    - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    - COMMIT_SHA=${DRONE_COMMIT_SHA}
    - REPOSITORY=codestation
    tags:
    - latest

  dockerhub-gogs:
    image: plugins/docker
    repo: codestation/gogs-s3-backup
    dockerfile: docker/gogs/Dockerfile
    mirror: https://registry-proxy.megpoid.xyz
    secrets:
    - source: dockerhub_username
      target: docker_username
    - source: dockerhub_password
      target: docker_password
    build_args:
    - REPOSITORY=codestation
    tags:
    - latest

  dockerhub-mysql:
    image: plugins/docker
    repo: codestation/mysql-s3-backup
    dockerfile: docker/mysql/Dockerfile
    mirror: https://registry-proxy.megpoid.xyz
    secrets:
    - source: dockerhub_username
      target: docker_username
    - source: dockerhub_password
      target: docker_password
    build_args:
    - REPOSITORY=codestation
    tags:
    - latest

  dockerhub-postgres:
    image: plugins/docker
    repo: codestation/postgres-s3-backup
    dockerfile: docker/postgres/Dockerfile
    mirror: https://registry-proxy.megpoid.xyz
    secrets:
    - source: dockerhub_username
      target: docker_username
    - source: dockerhub_password
      target: docker_password
    build_args:
    - REPOSITORY=codestation
    tags:
    - latest

  dockerhub-consul:
    image: plugins/docker
    repo: codestation/consul-s3-backup
    dockerfile: docker/consul/Dockerfile
    mirror: https://registry-proxy.megpoid.xyz
    secrets:
    - source: dockerhub_username
      target: docker_username
    - source: dockerhub_password
      target: docker_password
    build_args:
    - REPOSITORY=codestation
    tags:
    - latest

branches: master
