kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: golang:1.14
    commands:
      - go mod download
      - go install golang.org/x/lint/golint
      - go vet ./...
      - go test -v ./...
      - golint -set_exit_status `find . -type d -not -path "./vendor*" -not -path "./.git*"`

  - name: build
    image: registry.megpoid.xyz/drone-docker
    settings:
      repo: registry.megpoid.xyz/go-s3-backup
      registry: registry.megpoid.xyz
      mirror: http://mirror:5000
      tags: latest
      experimental: true
      stream: true
      target: builder
      push_target: true
      cache_from:
        - registry.megpoid.xyz/go-s3-backup:builder
        - registry.megpoid.xyz/go-s3-backup:latest
      build_args:
        - CI_TAG=${DRONE_TAG}
        - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
        - BUILD_COMMIT_SHORT=${DRONE_COMMIT_SHA:0:8}
        - CI_BUILD_CREATED=${DRONE_BUILD_CREATED}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    volumes:
      - name: cache
        path: /var/lib/docker

  - name: dockerhub
    image: plugins/docker
    settings:
      repo: codestation/go-s3-backup
      mirror: http://mirror:5000
      tags: latest
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      build_args:
        - CI_TAG=${DRONE_TAG}
        - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
        - BUILD_COMMIT_SHORT=${DRONE_COMMIT_SHA:0:8}
        - CI_BUILD_CREATED=${DRONE_BUILD_CREATED}
    volumes:
      - name: cache
        path: /var/lib/docker

trigger:
  branch:
    - master

volumes:
  - name: cache
    temp: {}
