kind: pipeline
name: default

steps:
  - name: test
    image: golang:1.12
    commands:
      - go install golang.org/x/lint/golint
      - go vet ./...
      - go test -v ./...
      - golint -set_exit_status `find . -type d -not -path "./vendor*" -not -path "./.git*"`
    environment:
      GO111MODULE: on
      GOFLAGS: -mod=vendor

  - name: build
    image: plugins/docker
    settings:
      repo: registry.megpoid.xyz/go-s3-backup
      registry: registry.megpoid.xyz
      mirror: http://mirror:5000
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
        - BUILD_COMMIT_SHORT=${DRONE_COMMIT_SHA:0:8}
    volumes:
      - name: cache
        path: /var/lib/docker

trigger:
  branch:
    - master

volumes:
  - name: cache
    temp: {}
